FROM python:3.8.18

# Crear directorio para la app y configurarlo como directorio de trabajo
RUN mkdir /app
WORKDIR /app

# Copiar los archivos desde el directorio 'web/api' al contenedor
ADD ./web/api /app

# Instalar las dependencias desde requirements.txt
RUN pip install -r /app/requirements.txt

# Exponer el puerto donde se ejecutará la API
EXPOSE 8080

# Usar gunicorn para ejecutar la aplicación Flask (en lugar de el servidor de desarrollo de Flask)
CMD ["gunicorn", "-b", "0.0.0.0:8080", "app:app"]